name: responsi_prak_mobile
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: BebasNeue # Nama font yang akan digunakan dalam Flutter
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf # Path ke file font
          weight: 400
  uses-material-design: true
